version: '3.8'

services:
  gisbackend:
    container_name: gisbackend
    image: gis-backend-gisbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn gisbackend.wsgi:application -b 0.0.0.0:9000
    ports:
      - 9000:9000
    networks:
      - live

  celery:
    container_name: giscelery
    image: gis-backend-gisbackend
    command: celery -A gisbackend.celery worker -l info -B --concurrency=5 
    pull_policy: never
    depends_on:
      - gisbackend
    networks:
      - live

  gis-redis:
    container_name: gis-redis
    image: redis:alpine
    hostname: redis
    restart : on-failure
    networks:
      - live

networks:
  live: