version: '3.8'

services:
  gisbackend:
    container_name: gisbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn gisbackend.wsgi:application -b 0.0.0.0:9000
    ports:
      - 9000:9000
    networks:
      - live

  celery:
    container_name: giscelery
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A gisbackend.celery worker -l info
    depends_on:
      - gisbackend
    networks:
      - live

  redis:
    image: redis:5.0.3-alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - live

networks:
  live: