# -*- coding: utf-8 -*-
"""TEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oPQXyEidTphx7ncjYSWAhdOBsaDIaId
"""

import geopandas as gpd
import requests
import json
import os
from sqlalchemy import create_engine
from sqlalchemy import text
import datetime

db_connection_url = "postgresql://tap_gis:T4pGreenGis88@postgresgis.tap-agri.com:5432/db_gis"
con = create_engine(db_connection_url)

host = 'https://django.tap-agri.com'
token ='Token 96188a88794241ebbd4c9594cb13fbc9f7b80dd2'

def sendAlert(featurescollections):
    data = json.loads(featurescollections)
    for ft in data['features']:
        try:
            attr = ft['properties']
            post = {
                'COMP' : int(attr['id']),
                'COMP_NAME' : attr['COMP_NAME'],
                'COMP_GROUP' : attr['COMP_GROUP'],
                #'EVENT_ID' : str(attr['UID']),
                'EVENT_DATE' : attr['DATE'],
                'EVENT_TIME' : attr['TIME'],
                'CONF' : int(attr['CONF']),
                'SATELLITE' : attr['SATELLITE'],
                'RADIUS' : int(attr['RADIUS']),
                'KECAMATAN' : attr['KECAMATAN'],
                'KEBUPATEN' : attr['KEBUPATEN'],
                'PROVINSI' : attr['PROVINSI'],
                'CATEGORY' : attr['CATEGORY'],
                'LONG': round(ft['geometry']['coordinates'][0], 3),
                'LAT': round(ft['geometry']['coordinates'][1], 3),
                'distance' : float(attr['distance']),
                'coordinates' : ft['geometry']['coordinates']
            }


            headers = {
                    "Content-Type": "application/json",
                    "Authorization" : token
            }
            print(post)
            response = requests.post(host + '/api/events/fires/company/', data=json.dumps(post), headers=headers)
            response.raise_for_status()
            print(response.json())
        except requests.exceptions.RequestException as e:
            print(f"Request failed with error:", e)
            continue
        except requests.exceptions.ConnectionError as e:
            print(f"Request failed with error:", e)
            continue   # If there was an error, continue to the ne#print(post)

    print("Update Finished")


def addcat(row):
    dist = float(row['distance'])
    if dist > 5000:
        return "AMAN"
    if dist > 1000 and dist <= 5000:
        return "PERHATIAN"
    if dist > 0 and dist <= 1000:
        return "WASPADA"
    if dist <= 0:
        return "BAHAYA"



def getNear(point, polygons):
    print(point.head(5))
    print(len(point))
    print(polygons.head(5))

    near = gpd.sjoin_nearest(point, polygons, distance_col="distance", max_distance=20000).to_crs(4326)
    #print(len(near))

    near['CREATED'] = near['CREATED'].astype(str)
    near['UPDATED'] = near['UPDATED'].astype(str)
    near['CATEGORY'] = near.apply(lambda row: addcat(row), axis=1)
    data = near.to_json()

    if len(near) > 0:
        sendAlert(data)
    else:
        print("No data for update")
        pass

def runProcessHotspot():
    table = "api_palms_company_list"
    column = "COMP_GROUP"
    value = "Triputra Group"
    #sql = "SELECT * FROM \"{}\" WHERE \"{}\" = \'{}\'".format(table, column, value)
    sql = "SELECT * FROM \"{}\"".format(table)
    polygons = gpd.GeoDataFrame.from_postgis(text(sql), con, geom_col='geom').to_crs("+proj=utm +zone=50 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")

    point = requests.get(host + '/api/hotspot/?conf=0&startdate={}&enddate={}'.format('2024-01-01', '2024-06-26'))
    print("HOTSPOT TODAY", point)
    point = json.dumps(point.json())
    point = gpd.read_file(point).to_crs("+proj=utm +zone=50 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
    getNear(point, polygons)

runProcessHotspot()

