# Generated by Django 3.2.1 on 2023-05-11 01:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIRE_HOTSPOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.BigIntegerField()),
                ('DATE', models.DateField(default=django.utils.timezone.now)),
                ('TIME', models.TimeField()),
                ('CONF', models.IntegerField()),
                ('SATELLITE', models.CharField(max_length=20)),
                ('RADIUS', models.IntegerField()),
                ('KECAMATAN', models.CharField(max_length=100)),
                ('KEBUPATEN', models.CharField(max_length=100)),
                ('PROVINSI', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['-UID'],
            },
        ),
        migrations.CreateModel(
            name='PALMS_COMPANY_LIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_NAME', models.CharField(max_length=250)),
                ('COMP_GROUP', models.CharField(blank=True, max_length=250, null=True)),
                ('CREATED', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='FIRE_EVENTS_ALERT_LIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_NAME', models.CharField(max_length=250)),
                ('COMP_GROUP', models.CharField(blank=True, max_length=250, null=True)),
                ('EVENT_ID', models.BigIntegerField()),
                ('EVENT_DATE', models.DateField(default=django.utils.timezone.now)),
                ('EVENT_TIME', models.TimeField()),
                ('CONF', models.IntegerField()),
                ('SATELLITE', models.CharField(max_length=20)),
                ('RADIUS', models.IntegerField()),
                ('KECAMATAN', models.CharField(max_length=100)),
                ('KEBUPATEN', models.CharField(max_length=100)),
                ('PROVINSI', models.CharField(max_length=100)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('STATUS', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=50, null=True)),
                ('CATEGORY', models.CharField(blank=True, choices=[('AMAN', 'AMAN'), ('PERHATIAN', 'PERHATIAN'), ('WASPADA', 'WASPADA'), ('BAHAYA', 'BAHAYA')], default='AMAN', max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('COMP', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comp_fire', to='api.palms_company_list')),
            ],
            options={
                'ordering': ['-EVENT_ID'],
            },
        ),
    ]
