# Generated by Django 3.2.1 on 2023-05-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palms_company_list',
            name='geojson',
            field=models.FileField(blank=True, null=True, upload_to='geojson', verbose_name='HGU_geojson_file'),
        ),
    ]
