# Generated by Django 3.2.1 on 2023-05-26 08:17

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_palms_company_list_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEFORESTATIONS_EVENTS_ALERT_LIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_ID', models.CharField(max_length=250)),
                ('ALERT_DATE', models.DateTimeField(default=django.utils.timezone.now)),
                ('CREATED', models.DateTimeField(default=django.utils.timezone.now)),
                ('UPDATED', models.DateTimeField(auto_now=True)),
                ('AREA', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('READ_BY', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('COMP', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comp_list', to='api.palms_company_list')),
            ],
            options={
                'ordering': ['-ALERT_DATE'],
            },
        ),
    ]
