# Generated by Django 3.2.1 on 2023-06-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deforestations_events_alert_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire_hotspot',
            name='LAT',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fire_hotspot',
            name='LONG',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fire_hotspot',
            name='SOURCE',
            field=models.CharField(blank=True, choices=[('LAPAN', 'LAPAN'), ('SIPONGI', 'SIPONGI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fire_hotspot',
            name='UID',
            field=models.CharField(max_length=250),
        ),
    ]
