# Generated by Django 3.2.1 on 2023-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230605_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire_events_alert_list',
            name='EVENT_ID',
            field=models.CharField(max_length=250),
        ),
    ]
