# Generated by Django 3.2.1 on 2023-06-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230605_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fire_events_alert_list',
            options={'ordering': ['-EVENT_DATE']},
        ),
    ]
