# Generated by Django 3.2.1 on 2023-06-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fire_events_alert_list_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fire_events_alert_list',
            name='EVENT_ID',
        ),
    ]
