# Generated by Django 3.2.1 on 2023-09-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fire_hotspot_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestations_events_alert_list',
            name='AREA',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
