# Generated by Django 3.2.1 on 2024-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_deforestations_events_alert_list_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deforestations_events_alert_list',
            old_name='AREA',
            new_name='HA',
        ),
        migrations.AddField(
            model_name='deforestations_events_alert_list',
            name='CONF',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
