# Generated by Django 3.2.1 on 2024-03-14 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20240312_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire_events_alert_list',
            name='UPDATE_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fire_hotspot',
            name='UPDATE_TIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
