# Generated by Django 3.2.1 on 2024-04-18 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_ha_deforestations_events_alert_list_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestations_events_alert_list',
            name='ALERT_DATE',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deforestations_events_alert_list',
            name='CREATED',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deforestations_events_alert_list',
            name='UPDATED',
            field=models.DateField(auto_now=True),
        ),
    ]
