# Generated by Django 3.2.1 on 2024-09-02 15:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMAT_LOCATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('werks', models.IntegerField()),
                ('afd_name', models.CharField(max_length=100)),
                ('block_name', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('soil', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('geojson', models.FileField(blank=True, null=True, upload_to='geojson', verbose_name='TMAT_geojson_file')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
    ]
