# Generated by Django 3.2.1 on 2024-09-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMAT_LOCATION_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('bulan', models.PositiveSmallIntegerField()),
                ('hari', models.PositiveSmallIntegerField()),
                ('periode', models.PositiveIntegerField()),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('input_date', models.CharField(blank=True, max_length=11, null=True)),
                ('tmat_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmat.tmat_locations')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tmat_location_data',
            constraint=models.CheckConstraint(check=models.Q(('bulan__gte', 1), ('bulan__lte', 12)), name='valid_bulan'),
        ),
        migrations.AddConstraint(
            model_name='tmat_location_data',
            constraint=models.CheckConstraint(check=models.Q(('hari__gte', 1), ('hari__lte', 31)), name='valid_hari'),
        ),
    ]
