# Generated by Django 3.2.1 on 2024-09-06 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmat', '0002_auto_20240903_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmat_location_data',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tmat_locations',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tmat_location_data',
            unique_together={('tmat_location', 'tahun', 'bulan', 'periode')},
        ),
    ]
